services:
  redis:
    image: redis:latest
    container_name: hanihome-redis-test
    ports:
      - "6380:6379"
    networks:
      - hanihome-test-net

networks:
  hanihome-test-net:
    driver: bridge