services: #컨테이너로 실행할 서비스들 정의, 여기선 백엔드랑 redis
  backend:
    build:
      context: . #현재 디렉토리에 있는 Dockerfile로 빌드
    container_name: hanihome-server #컨테이너 이름
    ports: #포트 로컬:컨테이너
      - "${SERVER_PORT}:8080"
    depends_on: #redis가 먼저 실행된 후 backend 실행
      - redis
    env_file:
      - .env
    environment: #환경변수
      - SPRING_DATASOURCE_URL=${DOCKER_SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      - SPRING_REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    networks: #hanohome-net이라는 네트워크로 연결됨 => 동일한 네트워크에서는 컨테이너 이름을 호스트네임처럼 사용하면서 서로 접근 가능
      - hanihome-net

  redis:
    image: redis:latest #최신이미지로 실행
    container_name: hanihome-redis #컨테이너 이름
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    networks:
      - hanihome-net

networks:
  hanihome-net: #네트워크 기본 방식 => 하니홈 백엔드 컨테이너에서 redi로 접근 가능
    driver: bridge



