spring:
  datasource:
    url: ${DOCKER_SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update     # 처음에는 update, 이후에는 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      connect-timeout: 5000
      timeout: 5000
      host: redis
      port: ${REDIS_CONTAINER_PORT}