[SERVICE]
    Flush         5
    Log_Level     debug
    Daemon        off

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224

[FILTER]
    Name                modify
    Match               hanihome.*
    Add                 service hanihome-backend
    Add                 environment local

[OUTPUT]
    Name              loki
    Match             *
    Host              loki
    Port              3100
    Labels            job=hanihome-backend,service=hanihome,environment=local,host=${HOSTNAME}
    Line_format       json
    Auto_kubernetes_labels off

[OUTPUT]
    Name              stdout
    Match             *